// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyOVMNMxHjfBi9__TuNHQSz3HOPGRYkaU',
    appId: '1:693457100519:web:38051b520edf978b71cc42',
    messagingSenderId: '693457100519',
    projectId: 'my-journal-b788d',
    authDomain: 'my-journal-b788d.firebaseapp.com',
    storageBucket: 'my-journal-b788d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTbQio0efQeHUnhIpadFvXuXpzNyQA0l8',
    appId: '1:693457100519:android:4726082a466f90d371cc42',
    messagingSenderId: '693457100519',
    projectId: 'my-journal-b788d',
    storageBucket: 'my-journal-b788d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdSMu58EU9vKvNFLrukGNt-nKH7Ol3v0w',
    appId: '1:693457100519:ios:2d1feb8a7dc2d96971cc42',
    messagingSenderId: '693457100519',
    projectId: 'my-journal-b788d',
    storageBucket: 'my-journal-b788d.appspot.com',
    iosClientId: '693457100519-ekbvc7mcapmm97clvms1c0vdntuob197.apps.googleusercontent.com',
    iosBundleId: 'com.example.myJournal',
  );
}
